spring.application.name=demo

# Configuración de la conexión a la base de datos
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bancoDB;trustServerCertificate=true;
spring.datasource.username=titu
spring.datasource.password=Residentevil5_??

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

#Formato Fechas
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss.SSS
spring.jackson.time-zone=America/Bogota

#Aplicar api a todas las URL
server.servlet.context-path=/api